aliases:
  - default
  - clean:prod
  - copy:prod
  - uglify
  - cssmin
clean:
  - '<%= dist %>'
copy:
  files:
    - 
      expand: true
      cwd: '<%= devDist %>'
      src: '**'
      dest: '<%= dist %>/'

