views:
  options:
    partials: views/partials/*.html
    data: data/*.yaml
  expand: true
  src: '*.html'
  cwd: views
  dest: '<%= devDist %>/'
watch:
  files:
    - views/**/*
    - data/*
  tasks:
    - views
